Dockerfile.rhel

We need to set io.openshift.release.operator true label for all images that go in release

Label azure provider image

---

pkg/cloud/azure/actuators/machine/actuator.go
pkg/cloud/azure/actuators/machine/actuator_test.go
pkg/cloud/azure/errors.go

In several CI examples linked within the BZ, we are seeing issues with the credentials just after they are created or rotated by the CCO. It looks like once the credentials are rotated they take a few minutes to propagate.
When the Machine already exists, this is fine because the exists call returns a 401 and we requeue. 
If a new machine is added, at the moment, the invalid credentials cause it to go into a failed phase, even though, if we retried slightly later, it is likely the create would have succeeded.
This PR changes the behaviour so that 401 errors (ie the credentials you provided weren't valid) no longer fails create.
I think this is safe as we already have a number of checks in place around credentials already. If the format of the secret, or any of the values are invalid, the …

Bug 2030488: Requeue create on invalid credentials errors

---

pkg/cloud/azure/actuators/machine/reconciler.go
pkg/cloud/azure/services/networkinterfaces/networkinterfaces.go

If we don't have the instance type in our cache, this panics.
We need to make sure that we can still handle unknown instance types, and so, if we don't know about them, just create the instance anyway and let Azure send an error back if the instance type is incompatible.
In the future, we should use the Azure API to look this information up dynamically.
CC @kwoodson

Bug 2085336: Ignore unknown Instance types in accelerated networking check

---

pkg/cloud/azure/actuators/machine/reconciler.go
pkg/cloud/azure/actuators/machine/reconciler_test.go

this change introduces logic to detect if the cluster name is already
present in the machineset name when generating the availability set
name. due to the fact that Azure has an 80 character limit on
availability set names[0], when the clsuter name is present in the
machineset name it is not added a second time. a test is also added for
this new logic.
[0]
https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/resource-name-rules#microsoftcompute

Bug 2093044: update getAvailabilitySetName function

---

pkg/cloud/azure/actuators/machineset/controller.go
pkg/cloud/azure/actuators/machineset/controller_test.go

Now we have a map of instance types that we compare provided values with. Unfortunately, type names are case-sensitive, which leads to an error. When, for instance, specifying `Standard_D8s_V4` instead of `Standard_D8s_v4` (V4 is specified instead of v4), Azure provider cannot find it in the map and fails to create an instance.
This commit converts all instance types in the map to a lower case and compares them with a string in a lower case as well.

Bug 2085390: make Azure instance types case-insensitive

---

pkg/cloud/azure/actuators/machine/reconciler.go
pkg/cloud/azure/decode/network.go
pkg/cloud/azure/services/interfaceloadbalancers/interfaceloadbalancers.go
pkg/cloud/azure/services/interfaceloadbalancers/interfaceloadbalancers_stack.go
pkg/cloud/azure/services/interfaceloadbalancers/service.go
pkg/cloud/azure/services/interfaceloadbalancers/service_stack.go

We have discovered that control plane machines must have an internal load balancer set, else they will not be able to be replaced. If the value isn't there, and we create a new Machine from the same spec, it will not join the internal load balancer and control plane components such as KCM will not be able to communicate with the API server.
As Azure only allows private or public load balancers, and you can only have one of each type, it's easy for us to look up, on a control plane machine, the internal load balancer if it isn't set. If the load balancer has a private IP front end, it has to be the internal load balancer, and it has to be the only internal load balancer.
This will only affect machines that don't have the internal load balancer set and should only happen once in the …

Bug 2117439: Populate internalLoadBalancer for Control Plane Machines when not set

---

pkg/cloud/azure/actuators/machine/reconciler.go
pkg/cloud/azure/actuators/machineset/controller.go
pkg/cloud/azure/services/networkinterfaces/networkinterfaces.go
pkg/cloud/azure/services/resourceskus/cache.go
pkg/cloud/azure/services/resourceskus/cache_test.go

This error needs to be InvalidMachineConfiguration, because machine goes failed only if it finds error of that type.

OCPBUGS-1871: Fix machine not going failed with invalid vmsize

---

pkg/cloud/azure/actuators/machine/reconciler.go

If machine creation fails, the MachineCreated condition in ProviderStatus is set to True instead of False.

OCPBUGS-3540: Fix MachineCreation condition having wrong status

---

pkg/cloud/azure/actuators/machine/reconciler.go
pkg/cloud/azure/services/availabilityzones/availabilityzones.go

Currently, the availability zones service can not determine zones presence in case if incorrect vmSize was passed.
This PR introduces special handling for empty vmSize argument within the availability zones service. In case vmSize is an empty string, the service will try to determine AZs presence within the region.

OCPBUGS-2123: Fix availability sets unwanted creation for unknown vmSizes

---

pkg/cloud/azure/actuators/machine_scope.go
pkg/cloud/azure/actuators/machine_scope_test.go

This was a mistake in a previous refactor, it used to set the name of the cluster object back when MAPI had a concept of cluster objects, it was renamed to set the MachineConfig name, however, that doesn't make sense now as it is setting the cluster name on the providerSpec. We should not be mutating the providerspec on every machine we create in this way, the value of this field is not used within the project anyway

OCPBUGS-5546: Machine Actuator should not set metadata.name

---

pkg/cloud/azure/actuators/machine/reconciler.go

We detect invalid VMsize and Accelerated Networking capability before creating the instance. And not attempt to create it when we know the configuration is invalid. 
We should still increment the mapi_instance_create_failed metric if we are unable to create the machine because of invalid VMsize or when accelerated networking is requested and not supported.

OCPBUGS-5235: Fix mapi_instance_create_failed metric with accelerated networking

---

pkg/cloud/azure/actuators/machine/reconciler.go
pkg/cloud/azure/actuators/machine_scope.go
pkg/cloud/azure/actuators/machine_scope_test.go

The assignment of MachineConfig.Name with clusterName was removed: https://github.com/openshift/machine-api-provider-azure/pull/47 As such the value resulted in an empty string, which was used in combination with the machineName strings to produce and invalid IP address name.
This should use a valid value for clusterName by fetching it from the infrastructure object.

OCPBUGS-7696: Fix empty clusterName references for GenerateMachinePublicIPName

---

pkg/cloud/azure/actuators/machine/actuator_test.go
pkg/cloud/azure/actuators/machine/reconciler.go

This PR removes the full error from the Reason field in RegisterFailedInstanceXXXX metrics, because it was causing the metric to have high/unbound cardinality. The full error is still logged, so this PR should not affect the ability to troubleshoot issues.

OCPBUGS-11223: Reduce metrics cardinality

---

pkg/cloud/azure/actuators/machine/actuator.go
pkg/cloud/azure/actuators/machine/reconciler.go
pkg/cloud/azure/actuators/machine/reconciler_test.go

When creating machine and attaching Azure Ultra Disks as Data Disks in Arm cluster, machine is Provisioned, but checked in azure web console, instance is failed with error ZonalAllocationFailed.
We want VMs that unexpectedly fail on Azure to also Fail appropriate machine in OpenShift. If we encounter this case, we don't want the `reconciler.Exists()` method to return an error, otherwise it would just try to reconcile the machine forerver.
We want to get the machine in a state, where the finalizers are removed and the machine is Failed.

OCPBUGS-10762: Machine should be Failed if Machine has a Failed state on Azure

---

go.mod
go.sum
pkg/cloud/azure/actuators/machineset/controller.go
pkg/cloud/azure/actuators/machineset/controller_test.go
pkg/cloud/azure/services/resourceskus/sku.go
vendor/github.com/openshift/machine-api-operator/pkg/util/util.go
vendor/modules.txt

This PR adds the `kubernetes.io/architecture` to the MachineSet labels `machine.openshift.io/labels` annotation so that the kubernetes-autoscaler can address the autoscale from 0 cases when a workload declares a `requiredAffinity` against a (set of) specific architecture(s).
This work is currently tested on a [custom backport](https://github.com/aleskandro/kubernetes-autoscaler/compare/openshift:kubernetes-autoscaler:master...master) of kubernetes/autoscaler#5697 and kubernetes/autoscaler#5382 and expects them to enable the architecture-aware autoscale from 0 working fine. 
Adding this feature now is harmless. After the rebase of the downstream kubernetes-autoscaler lands, it will start handling the autoscale from 0 for AWS multi-arch OCP clusters.
cc @Prashanth684 @elmiko @JoelSpeed …

MIXEDARCH-257: Handle the kubernetes.io/architecture label based on the Azure VM Size

---

pkg/cloud/azure/actuators/machineset/controller.go
pkg/cloud/azure/services/resourceskus/sku.go

As discussed last week, this PR resets the annotation for the arch-aware scale from 0 to the upstream labels capacity annotation so that we don't need to support both cases while transitioning to using the upstream annotations only.
This also fixes the hard-coded string with the capability name to get from the Azure APIs to catch the architecture of the workers.
/cc @elmiko

Set upstream labels and fix capability for the arch-aware scale from 0 in Azure

---

pkg/termination/termination_test.go

Unit tests are run in random order. Termination tests also verify the polling logic of the respective code, by atomically incrementing a counter in each call of the HTTP handler. The issues fixed with these changes are:
1. counter var not being reset after each termination test using polling
2. using the polling iterations loop in termination tests that were not using the HTTP handler that increments the counter
3. polling iterations loop not using sleep between iterations, which spikes CPU usage
The first two issues led to the termination tests sometimes passing, depending on which termination test run first. If it was a test that incremented the polling counter, then all other tests would be successful as well. If it was a test that didn't increment the polling counter (because it …

Fix termination tests randomly timing out

---

pkg/termination/termination_test.go

This change moves the bad url test to its own `Context` block so that it does not get caught in the mock termination service counter. In some cases it is possible for the bad url test to be run first, when this happens the counter will never advance because the url is not valid. This produces a dead lock condition in the test. Migrating the test to its own block alleviates this issue.
This change also updates the "not fulfilled" test to ensure that the counter is updated when the http handler is replaced.

OCPBUGS-20268: update bad url endpoint termination handler test

---

Makefile
hack/ci-test.sh
hack/goimports.sh
pkg/cloud/azure/actuators/machine/reconciler.go
pkg/cloud/azure/actuators/machine_scope.go
pkg/cloud/azure/actuators/machine_scope_test.go

Manual cherry-pick of #52 to fix up the test script which isn't working on the 4.12 branch currently

[release-4.12] OCPBUGS-22247,OCPBUGS-19549: Fix empty clusterName references for GenerateMachinePublicIPName

---

pkg/cloud/azure/actuators/machine/reconciler.go
pkg/cloud/azure/actuators/machine/reconciler_test.go

When we are on region without availability zones, we create availability sets for machinesets. This causes machines when using spot instances, because spot instances do not support availability sets. 
This PR disables implicit availability set creation when using spot instances.

OCPBUGS-25940: Don't create availability set when using spot instances

---

.snyk

this change is being added because the snyk scanning appears to pickup a vendor folder during the cachito expansion.

OCPBUGS-28309: add an extra vendor exclude to snyk config

---

pkg/cloud/azure/actuators/machine/reconciler.go

I believe this is some old alternative method of bootstrapping machines on azure. Considering VMExtension are not able to run on CoreOS as we don't ship with the Azure Extension Agent. This code does not make sense in current context.
Removing the entire if statement will create change in behavior of machines without UserDataSecret. Currently, the machine gets stuck in Provisioning phase, now It will get stuck in Provisioned. 
^ Needs to be verified

OCPBUGS-29956: Remove startupScript vmextension lookup

---

pkg/cloud/azure/actuators/machine/reconciler.go
pkg/cloud/azure/actuators/machine/reconciler_test.go
pkg/termination/termination_test.go

Combination of https://github.com/openshift/machine-api-provider-azure/pull/68 and  https://github.com/openshift/machine-api-provider-azure/pull/101

[release-4.13] OCPBUGS-29906: Don't create availability set when using spot instances

---

pkg/cloud/azure/services/availabilitysets/availabilitysets.go

I tried to dynamically set the amount of fault domains, install cluster with this pr on region "northcentralus", after installation scale up machineset, I can see the amount of fault domains is 3 instead of 2.  https://drive.google.com/file/d/1Rc1zCKts0gywhF_HyaoKm-xPfN_Snr-n/view?usp=sharing

OCPBUGS-45663: dynamically setting the amount of fault domains

---

pkg/cloud/azure/actuators/machine/reconciler.go
pkg/cloud/azure/actuators/machine/reconciler_test.go
pkg/cloud/azure/decode/virtualmachine.go

When the CCM populates the Zone label, if the zone is not populated in the VM properties, it falls back to the PlatformFaultDomain. This happens when using availability sets as availability sets are not compatible with availability zones.
See https://github.com/kubernetes-sigs/cloud-provider-azure/blob/b375c2a64ed15fa3ca1c170f12d608405f12b97d/pkg/provider/azure_standard.go#L583
This updates our zone fetching logic to implement the same fallback.

OCPBUGS-38570: Fallback to PlatformFaultDomain when Zones is otherwise unset

---

pkg/cloud/azure/actuators/machine/reconciler.go

Prior to this commit, MAPI only supports specifying a managed identity by name, and assumes that identity exists in the same resource group as the machine. This commit relaxes that requirement to allow a fully-specified id, to allow a managed identity from any resource group.
For background context openshift/installer#9538 removes the default managed-identity creation the installer has been creating since the beginning to authenticate cloud-provider-azure. With the move to out-of-tree, we have found that identity is no longer required as cloud-provider-azure is authenticated by credentials requests. Removing this automatic & unnecessary identity creation is a win for users, because they no longer need the Service Account Admin permission, which is a powerful permission.
On the other hand, …

CORS-3883: Allow managed identity from other resource groups

---

pkg/cloud/azure/actuators/machine/actuator_test.go
pkg/cloud/azure/actuators/machine/reconciler.go
pkg/cloud/azure/actuators/machine/reconciler_test.go
pkg/cloud/azure/decode/network.go
pkg/cloud/azure/services/networkinterfaces/networkinterfaces.go

Azure allows resources to enter a "ProvisioningFailed" state without returning an error from asynchronous operations. This can result in a cascading failure of dependent resources.
According to https://learn.microsoft.com/en-us/azure/networking/troubleshoot-failed-state#provisioning-states, to remedy this, the resource itself could be operational, but the last API action was a failure. Getting then re-submitting the resource should reset the provisioning state in such a case.
For our usage, we will re-queue a `Machine` until the NICs provision successfully, expecting subsequent reconciliations to correct the NIC's state.

OCPBUGS-31515: Re-reconcile machine on NIC provisioning failure

---

pkg/cloud/azure/services/virtualmachines/virtualmachines.go
pkg/cloud/azure/services/virtualmachines/virtualmachines_test.go

This fixes a bug where the spot machine was stuck in provisioned if it got deallocated before it was able to schedule the interruption handler. Now the machine will be deleted by Azure and go failed as expected.
It no longer says in the docs that Deallocate policy is not supported. I think that it is supported now. I am able to select delete policy in the Azure portal.
Therefore, I think we should switch to delete policy as this is preferred for our usecase.

OCPBUGS-54617: Update eviction policy for Spot VMs from Deallocate to Delete

---

pkg/cloud/azure/services/availabilitysets/availabilitysets.go

Recently, a change was made to make the fault domain count dynamic instead of using a fixed number. This led to the attempt of updating the availability sets that were using the old fixed fault domain count to the new value. As availability sets are immutable, except for tags. This resulted in failure to update the availability set. 
This PR changes the logic to not update the availability set. Except for tags that can be updated.

OCPBUGS-56380: Fix failure when attempting to modify immutable availabilitySet
